version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.BackgroundJob"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128
    target-branch: kinesis

  - package-ecosystem: "nuget"
    directory: "/MovementPass.Public.Api.BackgroundJob.Stack"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 128
    target-branch: kinesis
