name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: .NET setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6

      - name: Lambda.Tools install
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Release
        run: |
          dotnet restore
          cd MovementPass.Public.Api.BackgroundJob
          dotnet lambda package -o movement-pass_public-api-background-job_v1.zip

      - name: Update
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && env.AWS_REGION != '' }}
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.1
        with:
          zip-file: MovementPass.Public.Api.BackgroundJob/movement-pass_public-api-background-job_v1.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
